In [1]:
import numpy as np

In [2]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 11)

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [9]:
myA = np.array([10, 4, 2, 3])

In [11]:
myA[3]

np.int64(3)

In [12]:
myA

array([10,  4,  2,  3])

In [ ]:
##

## Other useful functions include

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [17]:
np.linspace(0, 0.1, 10)

array([0.        , 0.01111111, 0.02222222, 0.03333333, 0.04444444,
       0.05555556, 0.06666667, 0.07777778, 0.08888889, 0.1       ])

## Multi-dimensional arrays

In [18]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
a = np.array([
    [1, 5, 7],
    [2, 6, 8],
    [3, 7, 9],
])

In [24]:
a

array([[1, 5, 7],
       [2, 6, 8],
       [3, 7, 9]])

In [25]:
a[0][1]

np.int64(5)

In [26]:
a[0, 1]

np.int64(5)

In [30]:
a[:, 1]

array([5, 6, 7])

## Randomly Generated Arrays

In [32]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

If you want a normal distribution

In [37]:
100 * np.random.randn(5, 2)

array([[ 100.03658866,  -38.10925175],
       [ -37.56694231,   -7.44707629],
       [  43.34963301,  127.83792303],
       [ -63.46793052,   50.83962427],
       [  21.61160063, -185.86123861]])

In [40]:
np.random.randint(low=50, high=60, size=(5, 2))


array([[57, 54],
       [53, 56],
       [51, 54],
       [50, 58],
       [55, 54]], dtype=int32)

## Summarizing Operations
Such as max, min, sum, mean, std;

In [44]:
a = 10 * np.random.rand(5, 2)

In [45]:
a

array([[6.57512388, 2.14635746],
       [4.1675344 , 6.43841934],
       [6.61481327, 1.70477133],
       [8.81652236, 7.7800816 ],
       [1.33954208, 8.68916626]])

In [46]:
a.min()

np.float64(1.3395420817169101)